USE [Moderna]
GO

IF EXISTS (SELECT * FROM sys.objects WHERE [object_id] = OBJECT_ID(N'[dbo].[FACTURAS]') AND [type] = 'U')
BEGIN
	ALTER TABLE [dbo].[FACTURAS] DROP COLUMN MENSAJE_ERROR;  
END
GO

IF EXISTS (SELECT * FROM sys.objects WHERE [object_id] = OBJECT_ID(N'[dbo].[UPDATE_COMPROBANTE]') AND [type] = 'TR')
BEGIN
	DROP TRIGGER [dbo].[UPDATE_COMPROBANTE];
END
GO


IF EXISTS (SELECT * FROM sys.objects WHERE [object_id] = OBJECT_ID(N'[dbo].[INSERT_COMPROBANTE]') AND [type] = 'TR')
BEGIN
	DROP TRIGGER [dbo].[INSERT_COMPROBANTE];
END
GO

IF EXISTS (SELECT * FROM sys.objects WHERE [object_id] = OBJECT_ID(N'[dbo].[COMPROBANTE_AUDIT]') AND [type] = 'U')
BEGIN
	DROP TABLE [dbo].[COMPROBANTE_AUDIT];
END
GO

IF EXISTS (SELECT * FROM sys.objects WHERE [object_id] = OBJECT_ID(N'[dbo].[INSERT_COMPROBANTE_AUDIT]') AND [type] = 'TR')
BEGIN
	DROP TRIGGER [dbo].[INSERT_COMPROBANTE_AUDIT];
END
GO

IF EXISTS (SELECT * FROM sys.objects WHERE [object_id] = OBJECT_ID(N'[dbo].[COMPROBANTE]') AND [type] = 'U')
BEGIN
	DROP TABLE [dbo].[COMPROBANTE];
END
GO
