USE [Moderna]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[COMPROBANTE_AUDIT](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COMPROBANTE_ID] [int] NOT NULL,
	[FECHA] [datetime] NOT NULL,
	[CLAVE] [varchar](max) NULL,
	[NUMERO_CONSECUTIVO] [varchar](max) NULL,
	[IS_CORRECTO] [bit] NOT NULL,
	[ERROR] [varchar](max) NULL,
 CONSTRAINT [PK_COMPROBANTE_AUDIT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[COMPROBANTE_AUDIT]  WITH CHECK ADD  CONSTRAINT [FK_COMPROBANTE_AUDIT_COMPROBANTE] FOREIGN KEY([COMPROBANTE_ID])
REFERENCES [dbo].[COMPROBANTE] ([ID])
GO

ALTER TABLE [dbo].[COMPROBANTE_AUDIT] CHECK CONSTRAINT [FK_COMPROBANTE_AUDIT_COMPROBANTE]
GO
