USE [Moderna]
GO

/****** Object:  Trigger [dbo].[INSERT_COMPROBANTE_AUDIT]    Script Date: 9/15/2018 12:48:28 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TRIGGER [dbo].[INSERT_COMPROBANTE_AUDIT] ON [dbo].[COMPROBANTE]
FOR INSERT, UPDATE
AS

INSERT INTO COMPROBANTE_AUDIT
        (COMPROBANTE_ID, FECHA, CLAVE, NUMERO_CONSECUTIVO, IS_CORRECTO, ERROR)
    SELECT
        ID, GETDATE(), CLAVE, NUMERO_CONSECUTIVO, IIF (ERROR IS NULL OR ERROR = '', 1, 0),  ERROR
        FROM inserted

GO


