USE [Moderna]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET NOCOUNT ON
GO

CREATE TRIGGER [dbo].[UPDATE_COMPROBANTE] ON [dbo].[POS]
AFTER UPDATE
AS
UPDATE [dbo].[COMPROBANTE] 
SET 
  [EMISOR_IDENT_NUM] = (SELECT TOP 1 CONVERT(VARCHAR(50), DECRYPTBYPASSPHRASE('scab456', EMISOR)) FROM [dbo].[POS]), 
  [EMISOR_PROVINCIA] = (SELECT TOP 1 [provincia] FROM [dbo].[POS]),
  [EMISOR_CANTON] = (SELECT TOP 1 [CANTON] FROM [dbo].[POS]),
  [EMISOR_DISTRITO] = (SELECT TOP 1 [DISTRITO] FROM [dbo].[POS]),
  [EMISOR_OTRAS_SENAS] = (SELECT TOP 1 [OTRAS_SENAS] FROM [dbo].[POS])
