USE [Moderna]
GO

/****** Object:  Table [dbo].[COMPROBANTE_LINEA_DETALLE]    Script Date: 9/14/2018 1:23:01 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[COMPROBANTE_LINEA_DETALLE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[COMPROBANTE_ID] [int] NOT NULL,
	[NUMERO_LINEA] [int] NOT NULL,
	[CODIGO_TIPO] [varchar](2) NOT NULL,
	[CODIGO_COD] [varchar](50) NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[UNIDAD_MEDIDA] [varchar](50) NOT NULL,
	[DETALLE] [varchar](500) NOT NULL,
	[PRECIO_UNITARIO] [decimal](18, 2) NOT NULL,
	[MONTO_TOTAL] [decimal](18, 2) NOT NULL,
	[MONTO_DESCUENTO] [decimal](18, 2) NULL,
	[NATURALEZA_DESCUENTO] [varchar](100) NULL,
	[SUBTOTAL] [decimal](18, 2) NOT NULL,
	[IMPUESTO_CODIGO] [varchar](2) NULL,
	[IMPUESTO_TARIFA] [varchar](2) NULL,
	[IMPUESTO_MONTO] [decimal](18, 2) NULL,
	[MONTO_TOTAL_LINEA] [decimal](18, 2) NOT NULL,
 CONSTRAINT [PK_COMPROBANTE_LINEA_DETALLE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[COMPROBANTE_LINEA_DETALLE]  WITH CHECK ADD  CONSTRAINT [FK_COMPROBANTE_LINEA_DETALLE_COMPROBANTE_LINEA_DETALLE] FOREIGN KEY([COMPROBANTE_ID])
REFERENCES [dbo].[COMPROBANTE] ([ID])
GO

ALTER TABLE [dbo].[COMPROBANTE_LINEA_DETALLE] CHECK CONSTRAINT [FK_COMPROBANTE_LINEA_DETALLE_COMPROBANTE_LINEA_DETALLE]
GO
